

# About the Authors {-}


These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-give-credits).  
 
&nbsp;
&nbsp;
***In [memory](https://galaxyproject.org/jxtx/) of [James Taylor](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02016-0), who was instrumental in initiating this project.***

&nbsp;


|Credits|Names| 
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor|[Carrie Wright](https://carriewright11.github.io)|
|Content Contributors|[Candace Savonen](https://www.cansavvy.com/) (sections of Data Sharing, Data Security, Data Ethics, and quizzes)|
|Content Editors/Reviewers|[Candace Savonen](https://www.cansavvy.com/), [Jeff Leek](https://jtleek.com/), [Jodyn Platt](https://sph.umich.edu/faculty-profiles/platt-jodyn.html)|
|Content Directors| [Jeff Leek](https://jtleek.com/)|
|Content Consultant (General)| [Elana Fertig](https://fertiglab.com/)|
|Content Consultants (REDCap section)| Jennifer Durham|
|Acknowledgments ||
|**Production**||
|Content Publisher|[Ira Gooding](https://publichealth.jhu.edu/faculty/4130/ira-gooding)|
|Content Publishing Reviewers|[Ira Gooding](https://publichealth.jhu.edu/faculty/4130/ira-gooding), [Candace Savonen](https://www.cansavvy.com/)|
|**Technical**||
|Course Publishing Engineer|[Carrie Wright](https://carriewright11.github.io/)|
|Template Publishing Engineers|[Candace Savonen](https://www.cansavvy.com/), [Carrie Wright](https://carriewright11.github.io/) [Ava Hoffman]|
|Publishing Maintenance Engineer|[Candace Savonen](https://www.cansavvy.com/)|
|Technical Publishing Stylists|[Carrie Wright](https://carriewright11.github.io/), [Candace Savonen](https://www.cansavvy.com/)|
|Package Developers ([ottrpal](https://github.com/jhudsl/ottrpal))|[John Muschelli](https://johnmuschelli.com/), [Candace Savonen](https://www.cansavvy.com/), [Carrie Wright](https://carriewright11.github.io/)|
|**Art and Design**||
|Illustrator|[Carrie Wright](https://carriewright11.github.io)|
|**Funding**||
|Funder|[National Cancer Institute (NCI)](https://www.cancer.gov/) [UE5 CA254170](https://grantome.com/grant/NIH/UE5-CA254170-01)|
|Funding Staff| [Sandra Ormbrek], [Shasta Nicholson] |

[Ava Hoffman]: https://www.avahoffman.com/
[Sandra Ormbrek]: https://hutchdatascience.org/ourteam/
[Shasta Nicholson]: https://www.linkedin.com/in/shastanicholson/

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```
